export const constants = ({
    REQ_LOTERICA_JSON: 'REQ_LOTERICA_JSON',
    REC_LOTERICA_JSON: 'REC_LOTERICA_JSON',
    REQ_PROXIMO_ACUMULADOR: 'REQ_PROXIMO_ACUMULADOR',
    REC_PROXIMO_ACUMULADOR: 'REC_PROXIMO_ACUMULADOR',
    REQ_INCREASE: 'REQ_INCREASE'
})